### ISSUE TITLE
Varying max_sparsity from 0.1 to 0.9 for ALL Six pruners

### ISSUE THREAD

**Issue by tajwar12** [VainF/Torch-Pruning#204]
I have been trying to change the ch_sparsity for all the six pruners Random, L1, lamp, Slim, GroupNorm and Group_sl.
and then trying to compare the results that how much channel sparsity effects the accuracy.

I am also ploting Accuracies against level of sparsity. And I am using another neural architecture wideresnet.

for instance:
python main.py --mode prune --model wideresnet1 --batch-size 256 --dataset cifar10  --method random --speed-up 2.11 --total-epochs 25 --max-sparsity 0.1

If I run this command it rises the error:

Traceback (most recent call last):
  File "main.py", line 373, in <module>
    main()
  File "main.py", line 324, in main
    progressive_pruning(pruner, model, speed_up=args.speed_up, example_inputs=example_inputs)
  File "main.py", line 56, in progressive_pruning
    pruner.step(interactive=False)
  File "/home/muhammad.tajwar/.local/lib/python3.8/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 159, in step
    for group in self.prune_global():
  File "/home/muhammad.tajwar/.local/lib/python3.8/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 254, in prune_global
    imp = torch.cat([local_imp[-1]
RuntimeError: torch.cat(): expected a non-empty list of Tensors

this error is only for max_sparsity 0.1 , 0.2 and 0.3.

When try with max-sparsity 0.4 its starts pruning and finetuning.

Please guide me through this why it happened and whats the solution.I have also attached the graph what I am expecting.

Thanks in advance.

Kind Regards.
![Screenshot 2023-06-25 at 18 46 06](https://github.com/VainF/Torch-Pruning/assets/80433157/b148a658-a06c-429a-99f4-e41ee9c7c155)

**Comment by VainF** [comment]
Hi @tajwar12, I think this error was fixed in the latest commit. Feel free to @ me here if there are still some errors. Realy thanks for your information.

**Comment by tajwar12** [comment]
Hi @VainF , Thank you so much again for helping, But sorry the error still remains with max_sparsity = 0.1 the same error as aforementioned.

**Comment by tajwar12** [comment]
@VainF Hi I hope you are doing good.
I need to ask something about your work.

I have been trying to see how the ch_sparsity effects the accuracy of the neural network model. I am using CIFAR 10 dataset and wideresnet as a model.I am varying the ch_sparsity from 0.1 to 0.9 and measure the accuracy against them. state of the art we know that accuracy must decreases as we pruned the channels.

But the results are not as expected. I am attaching the screenshot I tried first with the random method by running this command:

python main.py --mode prune --model wideresnet1 --batch-size 256 --dataset cifar10  --method l1 --speed-up 2.11 --global-pruning --max-sparsity [0.1-0.9] --iterative-steps 100 --total-epochs 25

where --max-sparsity is varying from 0.1 to 0.9.

can you please explain why the accuracies have too fluctuations ? and even if you take a look at the graph you seen the accuracy increases from 0.2 to 0.4 and then decreases at 0.5 why its happening ? can you explain me this ? would be much appreciated. 

Thank you so much!
![random](https://github.com/VainF/Torch-Pruning/assets/80433157/00b36c2d-b1cd-4c40-a66e-361965a908e7)

and I am expecting from the results, I already uploaded a picture above if you see in my first issue.

**Comment by tajwar12** [comment]
Dear Gongfan Fang,
I hope you are doing well.

Thank you so much for fixing the error, now it works like a charm.

But I have raised another issue which is not a technical issue in the code
or any specific code related issue, now it's about the working of the
pruning algorithm.

I am using the magnitude pruning with the random method. but the results
are not as expected.

Please if you have some time give it a look and explain to me if I am doing
something wrong.

Thank you so much for your cooperation, it means a lot.

Kind regards.

**Comment by VainF** [comment]
max-sparsity is just an upperbound for pruning ratios. Please try different `speed-up`

**Comment by tajwar12** [comment]
> max-sparsity is just an upperbound for pruning ratios. Please try different `speed-up`

Thank you so much for replying Can you please elaborate more how speed-up effects the accuracy? 

and also for the ch_sparsity is it not how we are pruning the neurons in the layers ? that will eventually, effects accuracy.

for example in the screenshot below I dont understand the model initial accuracy is 0.9478 but after pruning at max_sparsity 0.1 the accuracy decreases to 0.865 then why the 1st epoch of the finetuning starts from 0.7212 it should starts from 0.865 I guess ? 

Please correct me If I am wrong.
![Screenshot 2023-06-30 at 16 43 16](https://github.com/VainF/Torch-Pruning/assets/80433157/f3492f29-6af4-4ef9-a155-014e3839d6bc)
